env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:vue/base
  - plugin:vue/vue3-recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: 
  - '@typescript-eslint/parser'
  - 'vue-eslint-parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  vueFeatures: 
    filter: true
    interpolationAsNonHTML: false
plugins:
  - vue
  - '@typescript-eslint'
rules: {}
